export const PACKING_CATEGORIES = [
  {
    id: 'docs',
    name: 'Documentos',
    emoji: '📄',
    items: [
      { id: 'd1', name: 'Pasaporte (vigente)', critical: true },
      { id: 'd2', name: 'Reservas de vuelo impresas o en teléfono', critical: true },
      { id: 'd3', name: 'Reservas de hotel/hostel', critical: true },
      { id: 'd4', name: 'Seguro de viaje (póliza impresa)', critical: true },
      { id: 'd5', name: 'Licencia de conducir (para el auto)', critical: true },
      { id: 'd6', name: 'Tarjetas de crédito/débito (2 mínimo)', critical: true },
      { id: 'd7', name: 'Efectivo en dólares (USD 200 por persona)', critical: true },
      { id: 'd8', name: 'Foto de todos los documentos en el teléfono', critical: true },
    ],
  },
  {
    id: 'ropa',
    name: 'Ropa',
    emoji: '👕',
    items: [
      { id: 'r1', name: 'Malla / bikini (2 por persona)', critical: false },
      { id: 'r2', name: 'Remeras de manga corta (5–6)', critical: false },
      { id: 'r3', name: 'Shorts (3–4)', critical: false },
      { id: 'r4', name: 'Pantalón largo (1 — para noches en Monteverde)', critical: false },
      { id: 'r5', name: 'Campera liviana / polar (para Monteverde — hace frío)', critical: true },
      { id: 'r6', name: 'Ropa impermeable / cortaviento', critical: false },
      { id: 'r7', name: 'Ropa interior (7 días)', critical: false },
      { id: 'r8', name: 'Medias (4 pares)', critical: false },
      { id: 'r9', name: 'Vestido / ropa de salir (1–2)', critical: false },
      { id: 'r10', name: 'Pijama liviano', critical: false },
    ],
  },
  {
    id: 'calzado',
    name: 'Calzado',
    emoji: '👟',
    items: [
      { id: 'c1', name: 'Zapatillas de trekking / senderismo (IMPRESCINDIBLE)', critical: true },
      { id: 'c2', name: 'Ojotas / chanclas para playa', critical: false },
      { id: 'c3', name: 'Zapatos para salir a cenar', critical: false },
    ],
  },
  {
    id: 'higiene',
    name: 'Higiene y salud',
    emoji: '🧴',
    items: [
      { id: 'h1', name: 'Repelente de insectos DEET 30%+ (el más importante)', critical: true },
      { id: 'h2', name: 'Protector solar FPS 50+ (mucho)', critical: true },
      { id: 'h3', name: 'Antihistamínico (para picaduras)', critical: true },
      { id: 'h4', name: 'Ibuprofeno / paracetamol', critical: true },
      { id: 'h5', name: 'Antidiarreico', critical: false },
      { id: 'h6', name: 'Crema corticoide (para picaduras)', critical: false },
      { id: 'h7', name: 'Curitas y vendas', critical: false },
      { id: 'h8', name: 'Champú, acondicionador, jabón', critical: false },
      { id: 'h9', name: 'Desodorante', critical: false },
      { id: 'h10', name: 'Pasta de dientes y cepillo', critical: false },
      { id: 'h11', name: 'Toalla de microfibra (los hostels no siempre proveen)', critical: false },
    ],
  },
  {
    id: 'tech',
    name: 'Tecnología',
    emoji: '📱',
    items: [
      { id: 't1', name: 'Teléfono desbloqueado + SIM tica o eSIM', critical: true },
      { id: 't2', name: 'Powerbank (10.000 mAh+)', critical: true },
      { id: 't3', name: 'Cargador universal', critical: true },
      { id: 't4', name: 'Cámara o cámara de acción (GoPro)', critical: false },
      { id: 't5', name: 'Auriculares', critical: false },
      { id: 't6', name: 'Adaptador de enchufe (Costa Rica usa tipo A/B — igual que Argentina)', critical: false },
      { id: 't7', name: 'Maps.me descargado offline (Costa Rica)', critical: true },
      { id: 't8', name: 'Spotify offline playlist', critical: false },
    ],
  },
  {
    id: 'actividades',
    name: 'Para actividades',
    emoji: '🌿',
    items: [
      { id: 'a1', name: 'Antiparras de natación / snorkel', critical: false },
      { id: 'a2', name: 'Aletas (opcional, las alquilan también)', critical: false },
      { id: 'a3', name: 'Bastones de trekking (plegables, opcionales)', critical: false },
      { id: 'a4', name: 'Bolsa impermeable / dry bag', critical: true },
      { id: 'a5', name: 'Mochila pequeña de día (20L)', critical: true },
      { id: 'a6', name: 'Linterna / head lamp', critical: false },
      { id: 'a7', name: 'Prismáticos para fauna (opcional pero copado)', critical: false },
    ],
  },
  {
    id: 'misc',
    name: 'Misceláneos',
    emoji: '🎒',
    items: [
      { id: 'm1', name: 'Candado pequeño para el hostel', critical: false },
      { id: 'm2', name: 'Bolsas ziploc (para playa / lluvia)', critical: false },
      { id: 'm3', name: 'Snacks energéticos para los senderos', critical: false },
      { id: 'm4', name: 'Botella de agua reutilizable (1L)', critical: true },
      { id: 'm5', name: 'Paraguas pequeño o poncho', critical: false },
      { id: 'm6', name: 'Almohada de cuello para el avión', critical: false },
    ],
  },
]

export const EMERGENCY_CONTACTS = [
  { name: 'Emergencias generales Costa Rica', phone: '911', category: 'emergencia' },
  { name: 'Cruz Roja Costa Rica', phone: '128', category: 'medico' },
  { name: 'Bomberos Costa Rica', phone: '118', category: 'emergencia' },
  { name: 'OIJ (Policía judicial)', phone: '800-8000-645', category: 'policia' },
  { name: 'Hospital Nacional de Niños', phone: '+506 2222-0122', category: 'medico' },
  { name: 'Hospital CIMA San José', phone: '+506 2208-1000', category: 'medico', note: 'Hospital privado, nivel internacional, inglés' },
  { name: 'Embajada Argentina en Costa Rica', phone: '+506 2234-6520', category: 'consulado' },
  { name: 'Adobe Rent a Car (auto)', phone: '+506 2232-5898', category: 'auto', note: 'Asistencia 24h en ruta' },
  { name: 'Seguro de viaje (anotar número de póliza)', phone: 'VER PÓLIZA', category: 'seguro' },
  { name: 'Taxi confiable San José — Taxis Unidos', phone: '+506 2221-6865', category: 'transporte' },
]
