export const HOTELS = [
  {
    id: 'h1',
    name: 'Casa Yoses Boutique Hotel',
    city: 'San José',
    area: 'Barrio Yoses',
    nights: 1,
    days: ['2026-01-16'],
    pricePerNight: 65,
    priceTotal: 65,
    rating: 4.6,
    reviews: 312,
    lat: 9.9329,
    lng: -84.0625,
    type: 'Boutique Hotel',
    bookingUrl: 'https://www.booking.com/hotel/cr/casa-yoses.html',
    website: 'https://www.casayoses.com',
    mapsUrl: 'https://maps.google.com/?q=Casa+Yoses+San+Jose+Costa+Rica',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600',
    pros: ['Ubicación perfecta — a pie del centro histórico', 'Desayuno incluido excelente', 'Jardín tropical tranquilo', 'Staff muy amable y con recomendaciones locales'],
    cons: ['Estacionamiento limitado (importante para el auto alquilado)', 'Habitaciones algo pequeñas'],
    parking: true,
    breakfast: true,
    pool: false,
    ac: true,
    wifi: true,
    bestFor: 'Primera y última noche — base para explorar San José',
    distanceFromCenter: '0.8 km del Teatro Nacional',
    checkIn: '14:00',
    checkOut: '12:00',
  },
  {
    id: 'h2',
    name: 'Lucky Bug Bed & Breakfast',
    city: 'La Fortuna',
    area: 'Arenal',
    nights: 2,
    days: ['2026-01-17', '2026-01-18'],
    pricePerNight: 75,
    priceTotal: 150,
    rating: 4.8,
    reviews: 487,
    lat: 10.4629,
    lng: -84.6507,
    type: 'B&B',
    bookingUrl: 'https://www.booking.com/hotel/cr/lucky-bug.html',
    website: 'https://www.luckybugbb.com',
    mapsUrl: 'https://maps.google.com/?q=Lucky+Bug+B%26B+La+Fortuna',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600',
    pros: ['Vista directa al Volcán Arenal', 'Desayuno espectacular incluido', 'Dueños locales con tips invaluables', 'Jardín con colibríes'],
    cons: ['Reservar con mucha anticipación — se llena rápido', '15 min en auto del centro de La Fortuna'],
    parking: true,
    breakfast: true,
    pool: false,
    ac: true,
    wifi: true,
    bestFor: 'Experiencia auténtica con vista al volcán',
    distanceFromCenter: '6 km del centro de La Fortuna',
    checkIn: '14:00',
    checkOut: '11:00',
  },
  {
    id: 'h3',
    name: 'Camino Verde B&B',
    city: 'Monteverde',
    area: 'Santa Elena',
    nights: 2,
    days: ['2026-01-19', '2026-01-20'],
    pricePerNight: 60,
    priceTotal: 120,
    rating: 4.7,
    reviews: 256,
    lat: 10.3145,
    lng: -84.8306,
    type: 'B&B',
    bookingUrl: 'https://www.booking.com/hotel/cr/camino-verde.html',
    website: 'https://www.caminoverdecostarica.com',
    mapsUrl: 'https://maps.google.com/?q=Camino+Verde+Monteverde',
    image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600',
    pros: ['Desayuno incluido con vista al bosque', 'A 5 min a pie de la reserva', 'Habitaciones cálidas y bien decoradas', 'Staff que conoce cada rincón del bosque'],
    cons: ['El camino de tierra para llegar tiene pozos', 'Frío de noche — llevá campera'],
    parking: true,
    breakfast: true,
    pool: false,
    ac: false,
    wifi: true,
    bestFor: 'Amantes de la naturaleza — lo más cerca del bosque nuboso',
    distanceFromCenter: '1.5 km del centro de Santa Elena',
    checkIn: '14:00',
    checkOut: '11:00',
  },
  {
    id: 'h4',
    name: 'Backpackers Manuel Antonio',
    city: 'Manuel Antonio',
    area: 'Zona turística',
    nights: 3,
    days: ['2026-01-21', '2026-01-22', '2026-01-23'],
    pricePerNight: 35,
    priceTotal: 105,
    rating: 4.4,
    reviews: 689,
    lat: 9.3942,
    lng: -84.1612,
    type: 'Hostel',
    bookingUrl: 'https://www.booking.com/hotel/cr/backpackers-manuel-antonio.html',
    website: 'https://www.hostelworld.com',
    mapsUrl: 'https://maps.google.com/?q=Backpackers+Manuel+Antonio',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600',
    pros: ['Precio muy accesible para la zona', 'Piscina con vista al Pacífico', 'Ambiente joven y viajero', 'A 5 min del parque nacional'],
    cons: ['Habitaciones compartidas (reservar habitación privada disponible +$)', 'Ruidoso los fines de semana'],
    parking: true,
    breakfast: false,
    pool: true,
    ac: true,
    wifi: true,
    bestFor: 'Viajeros con presupuesto ajustado que quieren estar cerca del parque',
    distanceFromCenter: '200m de la entrada al Parque Nacional',
    checkIn: '14:00',
    checkOut: '11:00',
  },
  {
    id: 'h5',
    name: 'Tucan Hotel Uvita',
    city: 'Uvita',
    area: 'Bahía Ballena',
    nights: 2,
    days: ['2026-01-24', '2026-01-25'],
    pricePerNight: 45,
    priceTotal: 90,
    rating: 4.5,
    reviews: 198,
    lat: 9.1516,
    lng: -83.7329,
    type: 'Hotel Boutique',
    bookingUrl: 'https://www.booking.com/hotel/cr/tucan-uvita.html',
    website: 'https://www.tucanhoteluvita.com',
    mapsUrl: 'https://maps.google.com/?q=Tucan+Hotel+Uvita',
    image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600',
    pros: ['Piscina en medio del jardín tropical', 'Personal local encantador', 'A 5 min a pie de la Cola de la Ballena', 'Desayuno incluido excelente'],
    cons: ['Poca variedad gastronómica en Uvita', 'Internet lento'],
    parking: true,
    breakfast: true,
    pool: true,
    ac: true,
    wifi: true,
    bestFor: 'Descanso real — el lugar más tranquilo de la ruta',
    distanceFromCenter: '800m del centro de Uvita',
    checkIn: '14:00',
    checkOut: '11:00',
  },
  {
    id: 'h6',
    name: 'Hotel Presidente San José',
    city: 'San José',
    area: 'Centro Histórico',
    nights: 4,
    days: ['2026-01-26', '2026-01-27', '2026-01-28', '2026-01-29'],
    pricePerNight: 80,
    priceTotal: 320,
    rating: 4.3,
    reviews: 1245,
    lat: 9.9325,
    lng: -84.0798,
    type: 'Hotel',
    bookingUrl: 'https://www.booking.com/hotel/cr/presidente.html',
    website: 'https://www.hotel-presidente.com',
    mapsUrl: 'https://maps.google.com/?q=Hotel+Presidente+San+Jose',
    image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600',
    pros: ['Ubicación central inmejorables', 'Restaurante propio muy bueno', 'Estacionamiento incluido', 'Ideal para la última parte del viaje con todo a pie'],
    cons: ['Área del centro algo bulliciosa de noche', 'Sin piscina'],
    parking: true,
    breakfast: false,
    pool: false,
    ac: true,
    wifi: true,
    bestFor: 'Últimos días — museos, restaurantes, compras y aeropuerto cercano',
    distanceFromCenter: '0 km — EN el centro histórico',
    checkIn: '15:00',
    checkOut: '12:00',
  },
]

export const TOTAL_ACCOMMODATION = HOTELS.reduce((acc, h) => acc + h.priceTotal, 0)
