export const RESTAURANTS = [
  {
    id: 'r1',
    name: 'El Avión',
    city: 'Manuel Antonio',
    cuisine: 'Mariscos / Fusión',
    priceRange: '$$$',
    avgCost: 30,
    rating: 4.7,
    reviews: 2890,
    lat: 9.3914,
    lng: -84.1597,
    mapsUrl: 'https://maps.google.com/?q=El+Avion+Manuel+Antonio',
    website: 'https://www.elavion.com',
    mustOrder: ['Corvina en salsa de maracuyá', 'Camarones al ajillo', 'Ceviche tico'],
    reservationRequired: true,
    parking: true,
    description: 'Restaurante DENTRO de un avión Fairchild C-123 de la era del escándalo Irán-Contra. Vista al mar y cocina de mariscos excepcional.',
    tip: 'Pedí mesa afuera al atardecer — las vistas son épicas. Reservá con 2 días de anticipación mínimo.',
    dayInTrip: 6,
    category: 'imperdible',
  },
  {
    id: 'r2',
    name: 'Don Rufino',
    city: 'La Fortuna',
    cuisine: 'Parrilla / Tica',
    priceRange: '$$$',
    avgCost: 28,
    rating: 4.6,
    reviews: 3420,
    lat: 10.4677,
    lng: -84.6444,
    mapsUrl: 'https://maps.google.com/?q=Don+Rufino+La+Fortuna',
    website: 'https://www.donrufino.com',
    mustOrder: ['Lomo al trapo', 'Gallo pinto con natilla', 'Patacones con guacamol'],
    reservationRequired: false,
    parking: true,
    description: 'El mejor restaurante de La Fortuna. Vista directa al Volcán Arenal desde la terraza. Parrilla de primer nivel con ingredientes locales.',
    tip: 'Llegá 30 min antes del sunset para conseguir mesa afuera con vista al volcán.',
    dayInTrip: 3,
    category: 'imperdible',
  },
  {
    id: 'r3',
    name: 'Nuestra Tierra',
    city: 'San José',
    cuisine: 'Costarricense típica',
    priceRange: '$$',
    avgCost: 22,
    rating: 4.5,
    reviews: 4102,
    lat: 9.9340,
    lng: -84.0812,
    mapsUrl: 'https://maps.google.com/?q=Nuestra+Tierra+San+Jose',
    website: 'https://www.nuestratierra.com',
    mustOrder: ['Casado con costillas', 'Chifrijo', 'Pozol de frijoles', 'Tres leches de postre'],
    reservationRequired: false,
    parking: false,
    description: 'Cocina tica de la abuela: marimba en vivo, decoración de hacienda y los mejores casados de San José. Abierto las 24 horas.',
    tip: 'Si llegás de noche tarde, está abierto — ideal para la primera o última noche en San José.',
    dayInTrip: 11,
    category: 'clasico',
  },
  {
    id: 'r4',
    name: 'Park Café',
    city: 'San José',
    cuisine: 'Cocina de autor / Fusión',
    priceRange: '$$$$',
    avgCost: 40,
    rating: 4.8,
    reviews: 892,
    lat: 9.9412,
    lng: -84.0956,
    mapsUrl: 'https://maps.google.com/?q=Park+Cafe+San+Jose',
    website: 'https://www.parkcafecostarica.com',
    mustOrder: ['Menú degustación 5 pasos', 'Ceviche deconstruido', 'Coulant de chocolate con café tico'],
    reservationRequired: true,
    parking: false,
    description: 'Solo 8 mesas. El restaurante más galardonado de Costa Rica. Cocina de autor con ingredientes locales en un antiguo antique shop. Experiencia gastronómica única.',
    tip: 'Reservá con mínimo 1 semana de anticipación. Solo tiene 8 mesas — se llena siempre.',
    dayInTrip: 12,
    category: 'experiencia',
  },
  {
    id: 'r5',
    name: "Morpho's Restaurant",
    city: 'Monteverde / Santa Elena',
    cuisine: 'Tica / Internacional',
    priceRange: '$$',
    avgCost: 20,
    rating: 4.5,
    reviews: 1678,
    lat: 10.3172,
    lng: -84.8253,
    mapsUrl: 'https://maps.google.com/?q=Morpho+Restaurant+Monteverde',
    website: null,
    mustOrder: ['Tamales en hoja', 'Corazón de palmito salteado', 'Batido de maracuyá'],
    reservationRequired: false,
    parking: false,
    description: 'El favorito de los locales en Santa Elena. Porciones generosas, precios justos y el mejor batido de maracuyá de Monteverde.',
    tip: 'Llegá antes de las 19:30 — se llena rápido y no aceptan reservas.',
    dayInTrip: 4,
    category: 'local',
  },
  {
    id: 'r6',
    name: 'Sikwa',
    city: 'San José',
    cuisine: 'Cocina indígena costarricense',
    priceRange: '$$$',
    avgCost: 35,
    rating: 4.6,
    reviews: 445,
    lat: 9.9348,
    lng: -84.0834,
    mapsUrl: 'https://maps.google.com/?q=Sikwa+San+Jose',
    website: 'https://www.sikwarestaurant.com',
    mustOrder: ['Menú indígena completo', 'Chicha fermentada', 'Pupusas de maíz nativo', 'Postre de pejibaye'],
    reservationRequired: true,
    parking: false,
    description: 'El único restaurante de cocina indígena de Costa Rica. Chef Pablo Bonilla rescata recetas de las 8 culturas originarias. Experiencia cultural gastronómica única en el país.',
    tip: 'La cena de despedida ideal. Reservá con anticipación. Es pequeño y muy especial.',
    dayInTrip: 14,
    category: 'experiencia',
  },
  {
    id: 'r7',
    name: 'La Cantina Uvita',
    city: 'Uvita',
    cuisine: 'Mariscos / Ceviche',
    priceRange: '$',
    avgCost: 15,
    rating: 4.4,
    reviews: 234,
    lat: 9.1501,
    lng: -83.7312,
    mapsUrl: 'https://maps.google.com/?q=La+Cantina+Uvita',
    website: null,
    mustOrder: ['Ceviche de pulpo', 'Taco de pargo rojo', 'Limonada con jengibre'],
    reservationRequired: false,
    parking: true,
    description: 'Soda familiar con mariscos frescos del día. Lo más rico de Uvita al mejor precio. El ceviche de pulpo es legendary entre los viajeros.',
    tip: 'El ceviche cambia según la pesca del día — pedí siempre lo que acaba de llegar.',
    dayInTrip: 9,
    category: 'local',
  },
  {
    id: 'r8',
    name: 'Agua Azul',
    city: 'Manuel Antonio',
    cuisine: 'Mariscos / Vista al mar',
    priceRange: '$$$',
    avgCost: 30,
    rating: 4.5,
    reviews: 1890,
    lat: 9.3945,
    lng: -84.1623,
    mapsUrl: 'https://maps.google.com/?q=Agua+Azul+Manuel+Antonio',
    website: 'https://www.aguaazulma.com',
    mustOrder: ['Langosta a la plancha', 'Rondon (sopa caribeña)', 'Piña colada natural'],
    reservationRequired: false,
    parking: true,
    description: 'Terraza abierta sobre el Pacífico con las mejores vistas de Manuel Antonio. Perfecta para cenas tranquilas viendo las luces del mar.',
    tip: 'Llegá a las 18:00 para el golden hour. Las tortugas aparecen a veces en la playa abajo.',
    dayInTrip: 8,
    category: 'vistas',
  },
]
