export const EXCURSIONS = [
  {
    id: 'ex1',
    name: 'Tour Bosque Nuboso con Guía — Quetzales',
    location: 'Monteverde',
    region: 'Monteverde',
    lat: 10.2994,
    lng: -84.8198,
    duration: '3 horas',
    difficulty: 'Fácil-Moderado',
    price: 45,
    company: 'Reserva Bosque Nuboso Monteverde',
    website: 'https://www.cloudforestmonteverde.com',
    bookingUrl: 'https://www.cloudforestmonteverde.com/tours',
    included: ['Guía experto bilingüe', 'Entrada a la reserva', 'Equipo de observación'],
    notIncluded: ['Propinas', 'Transporte al parque', 'Comida'],
    cancellation: 'Cancelación gratuita hasta 24h antes',
    worthIt: true,
    rating: 4.9,
    reviews: 2340,
    reviewSummary: 'Unanimidad: sin guía no se ve fauna. El guía hace la diferencia total. La mayoría ve quetzales en enero.',
    emoji: '🦜',
    bestTime: 'Amanecer (6:30–7:00am)',
    category: 'naturaleza',
  },
  {
    id: 'ex2',
    name: 'Sky Trek — Tirolesas Extremas',
    location: 'Monteverde',
    region: 'Monteverde',
    lat: 10.3052,
    lng: -84.8231,
    duration: '3–4 horas',
    difficulty: 'Fácil (se puede hacer sin experiencia)',
    price: 75,
    company: 'Sky Adventures Costa Rica',
    website: 'https://www.skyadventures.travel',
    bookingUrl: 'https://www.skyadventures.travel/monteverde',
    included: ['10 cables de tirolesa', 'Guías y equipo de seguridad', 'Transfer al inicio'],
    notIncluded: ['Fotos (se compran por separado)', 'Propinas', 'Comida'],
    cancellation: 'Cancelación 24h antes 100%, 12h antes 50%',
    worthIt: true,
    rating: 4.7,
    reviews: 5890,
    reviewSummary: 'El cable más largo mide 750m con 100m de altura. Experiencia épica. Casi nadie se arrepiente aunque tenga miedo.',
    emoji: '🪂',
    bestTime: 'Mañana antes de las nubes',
    category: 'aventura',
  },
  {
    id: 'ex3',
    name: 'Eco Termales Hot Springs',
    location: 'La Fortuna',
    region: 'Arenal',
    lat: 10.4756,
    lng: -84.6901,
    duration: '3 horas',
    difficulty: 'Sin dificultad',
    price: 45,
    company: 'Eco Termales Fortuna',
    website: 'https://www.ecotermalesfortuna.cr',
    bookingUrl: 'https://www.ecotermalesfortuna.cr/reservaciones',
    included: ['Acceso a todas las piscinas termales', 'Casilleros', 'Ducha'],
    notIncluded: ['Comida y bebidas (hay restaurante en el lugar)', 'Transporte'],
    cancellation: 'Cancelación hasta 48h antes sin cargo',
    worthIt: true,
    rating: 4.8,
    reviews: 3201,
    reviewSummary: 'Mucho mejor que Tabacón — menos gente, mismo calor, mejor precio. Piscinas de agua 37-40°C con vista al volcán de noche.',
    emoji: '♨️',
    bestTime: 'Noche (18:00–21:00) para ver el volcán',
    category: 'relajacion',
  },
  {
    id: 'ex4',
    name: 'Tour Avistamiento de Ballenas y Delfines',
    location: 'Uvita',
    region: 'Pacífico Sur',
    lat: 9.1516,
    lng: -83.7329,
    duration: '4 horas',
    difficulty: 'Sin dificultad',
    price: 75,
    company: 'Bahía Aventuras',
    website: 'https://www.bahiaaventuras.com',
    bookingUrl: 'https://www.bahiaaventuras.com/reservaciones',
    included: ['Bote privado', 'Guía naturalista', 'Snorkel y equipo', 'Refrigerio a bordo', 'Seguro'],
    notIncluded: ['Transporte al muelle', 'Propinas (recomendadas)', 'Fotos'],
    cancellation: 'Cancelación 48h antes sin cargo. Si no hay ballenas, tour completo de snorkel.',
    worthIt: true,
    rating: 4.9,
    reviews: 1876,
    reviewSummary: 'Enero es temporada perfecta para ballenas jorobadas en migración. 95% de éxito en avistamiento. Además: delfines nariz de botella y tortugas.',
    emoji: '🐋',
    bestTime: 'Enero es la mejor época del año',
    category: 'vida-marina',
  },
  {
    id: 'ex5',
    name: 'Kayak en Lago Arenal',
    location: 'La Fortuna',
    region: 'Arenal',
    lat: 10.4808,
    lng: -84.7901,
    duration: '2.5 horas',
    difficulty: 'Fácil',
    price: 35,
    company: 'Desafío Kayaks',
    website: 'https://www.desafiocr.com',
    bookingUrl: 'https://www.desafiocr.com/kayak-arenal',
    included: ['Kayak y paleta', 'Chaleco salvavidas', 'Guía', 'Seguro'],
    notIncluded: ['Transporte al lago', 'Propinas'],
    cancellation: 'Cancelación libre hasta 24h antes',
    worthIt: true,
    rating: 4.6,
    reviews: 987,
    reviewSummary: 'El lago Arenal con el volcán al fondo es una de las vistas más épicas de Costa Rica. Mejor muy temprano cuando el agua está calma.',
    emoji: '🛶',
    bestTime: '7:00–9:00am — agua calma y volcán despejado',
    category: 'aventura',
  },
  {
    id: 'ex6',
    name: 'Tour Volcán Poás al Amanecer',
    location: 'San José / Valle Central',
    region: 'Valle Central',
    lat: 10.1966,
    lng: -84.2286,
    duration: '5 horas ida y vuelta',
    difficulty: 'Fácil',
    price: 18,
    company: 'SINAC (Parque Nacional)',
    website: 'https://www.sinac.go.cr',
    bookingUrl: 'https://sinac.go.cr/reservaciones-parques',
    included: ['Entrada al parque', 'Sendero al cráter y a la Laguna Botos'],
    notIncluded: ['Transporte (auto propio o tour organizado)', 'Guía (opcional, recomendado)', 'Comida'],
    cancellation: 'Cancelación libre',
    worthIt: true,
    rating: 4.7,
    reviews: 6780,
    reviewSummary: 'El cráter turquesa activo más accesible del mundo. Llegá antes de las 8am porque se llena de nubes. Vistas lunares del cráter principal.',
    emoji: '🌋',
    bestTime: '7:00–9:00am antes de las nubes',
    category: 'naturaleza',
  },
]

export const BEACHES = [
  {
    id: 'b1',
    name: 'Playa Manuel Antonio',
    region: 'Pacífico Central',
    lat: 9.3773,
    lng: -84.1543,
    mapsUrl: 'https://maps.google.com/?q=Playa+Manuel+Antonio',
    description: 'La playa más famosa de Costa Rica. Dentro del parque nacional, rodeada de selva y con monos caminando en la arena.',
    parking: true,
    facilities: ['Baños', 'Duchas', 'Quioscos de comida'],
    crowded: 'Alto en temporada alta — llegá antes de las 8am',
    swimming: true,
    surf: false,
    snorkel: true,
    sunset: false,
    bestTimeToVisit: 'Mañana temprano (7:00–10:00am)',
    tip: 'Está dentro del Parque Nacional — necesitás reservar entrada online. Los monos roban comida.',
    rating: 4.8,
    dayInTrip: 7,
  },
  {
    id: 'b2',
    name: 'Playa Biesanz',
    region: 'Pacífico Central',
    lat: 9.3895,
    lng: -84.1598,
    mapsUrl: 'https://maps.google.com/?q=Playa+Biesanz+Manuel+Antonio',
    description: 'La playa escondida de Manuel Antonio. Pequeña, tranquila y casi siempre sin mucha gente. La mejor para snorkel de la zona.',
    parking: false,
    facilities: ['Ninguna — trae todo lo tuyo'],
    crowded: 'Bajo — pocos la conocen',
    swimming: true,
    surf: false,
    snorkel: true,
    sunset: false,
    bestTimeToVisit: 'Cualquier hora — la menos concurrida',
    tip: 'Buscala exactamente en Google Maps — el acceso no está señalizado. Vale mucho la pena.',
    rating: 4.7,
    dayInTrip: 6,
  },
  {
    id: 'b3',
    name: 'Playa Espadilla',
    region: 'Pacífico Central',
    lat: 9.3951,
    lng: -84.1656,
    mapsUrl: 'https://maps.google.com/?q=Playa+Espadilla+Manuel+Antonio',
    description: 'La playa pública principal de Manuel Antonio. Larga, con olas perfectas para surf y acceso libre sin entrada al parque.',
    parking: true,
    facilities: ['Baños', 'Duchas', 'Restaurantes', 'Alquiler de tablas'],
    crowded: 'Medio — más espacio que Manuel Antonio',
    swimming: true,
    surf: true,
    snorkel: false,
    sunset: true,
    bestTimeToVisit: 'Tarde para el sunset',
    tip: 'Clases de surf disponibles desde $35 por 2 horas con instructores locales.',
    rating: 4.5,
    dayInTrip: 8,
  },
  {
    id: 'b4',
    name: 'Cola de la Ballena — Uvita',
    region: 'Pacífico Sur',
    lat: 9.1479,
    lng: -83.7271,
    mapsUrl: 'https://maps.google.com/?q=Cola+de+Ballena+Uvita',
    description: 'La formación natural de arena en forma de cola de ballena que solo aparece con marea baja. Uno de los fenómenos naturales más únicos del mundo.',
    parking: true,
    facilities: ['Baños', 'Kioscos de comida afuera del parque'],
    crowded: 'Bajo — Uvita es tranquilo',
    swimming: true,
    surf: false,
    snorkel: true,
    sunset: true,
    bestTimeToVisit: 'Marea baja — verificar horario en advance',
    tip: 'La "cola" solo aparece con marea baja. Chequeá el horario de mareas antes de ir. El sunset desde acá es espectacular.',
    rating: 4.9,
    dayInTrip: 9,
  },
]
