export const TRIP = {
  name: 'Pura Vida 🌿',
  travelers: ['Dai', 'Juli', 'Gonza'],
  startDate: '2026-01-16',
  endDate: '2026-01-31',
  nights: 15,
  arrival: 'Aeropuerto Juan Santamaría (SJO), San José, Costa Rica',
  departure: 'Aeropuerto Juan Santamaría (SJO), San José, Costa Rica',
  currency: 'USD',
  hashtag: '#PuraVidaDJG',
}

export const ITINERARY = [
  {
    day: 1,
    date: '2026-01-16',
    title: 'Llegada a San José',
    emoji: '✈️',
    region: 'San José',
    lat: 9.9281,
    lng: -84.0907,
    theme: 'Llegada y primer sabor tico',
    description: 'Aterrizaje, recogida del auto y primer contacto con la pura vida. Noche tranquila en San José.',
    accommodation: 'Casa Yoses Boutique Hotel',
    meals: {
      breakfast: null,
      lunch: 'Mercado Central de San José — casado típico',
      dinner: 'Restaurante La Criollita — cocina costarricense clásica',
    },
    activities: [
      { time: '14:00', name: 'Recogida del auto 4x4 (Adobe Rent a Car)', duration: '1h', cost: 0, note: 'Incluido en alquiler diario' },
      { time: '15:30', name: 'Check-in hotel y descanso', duration: '1h', cost: 0 },
      { time: '17:00', name: 'Barrio Amón — arquitectura colonial', duration: '1.5h', cost: 0, note: 'Paseo a pie gratis' },
      { time: '19:00', name: 'Cena en La Criollita', duration: '1.5h', cost: 15 },
    ],
    drivingToNext: { destination: 'La Fortuna', km: 140, hours: 3 },
    tips: ['Cargá el tanque en San José, es más barato que en zonas turísticas', 'El GPS funciona bien pero descargá Maps.me offline', 'Usá colones para la comida en el Mercado Central'],
    budget: { accommodation: 65, food: 35, activities: 0, transport: 40, total: 140 },
  },
  {
    day: 2,
    date: '2026-01-17',
    title: 'Camino a La Fortuna — Volcán Arenal',
    emoji: '🌋',
    region: 'Arenal',
    lat: 10.4626,
    lng: -84.7032,
    theme: 'El volcán más famoso de Centroamérica',
    description: 'Salida temprana hacia La Fortuna. Tarde libre para explorar el pueblo y primer avistamiento del Arenal.',
    accommodation: 'Lucky Bug Bed & Breakfast',
    meals: {
      breakfast: 'Desayuno en el hotel',
      lunch: 'Rancho La Cascada — frente al Arenal',
      dinner: 'El Novillo del Arenal — parrilla tica',
    },
    activities: [
      { time: '07:00', name: 'Salida de San José hacia La Fortuna', duration: '3h drive', cost: 0 },
      { time: '10:30', name: 'Parada en Ciudad Quesada — café y patas de res', duration: '45min', cost: 8 },
      { time: '12:00', name: 'Check-in y almuerzo en La Fortuna', duration: '1.5h', cost: 20 },
      { time: '14:00', name: 'Catarata La Fortuna', duration: '2.5h', cost: 18, note: '500 escalones de bajada y subida — valen la pena' },
      { time: '17:00', name: 'Paseo al mirador del volcán (gratis desde la ruta)', duration: '1h', cost: 0 },
      { time: '19:00', name: 'Cena con vista al Arenal', duration: '1.5h', cost: 20 },
    ],
    drivingToNext: { destination: 'Continúa en La Fortuna', km: 0, hours: 0 },
    tips: ['La Catarata La Fortuna — llegá antes de las 9am para evitar multitudes', 'Si el volcán está despejado de noche, mirá desde el hotel', 'Reservá las termas con anticipación'],
    budget: { accommodation: 75, food: 55, activities: 18, transport: 20, total: 168 },
  },
  {
    day: 3,
    date: '2026-01-18',
    title: 'Arenal — Termas y Lago',
    emoji: '♨️',
    region: 'Arenal',
    lat: 10.4626,
    lng: -84.7032,
    theme: 'Naturaleza, agua y relajación',
    description: 'Día completo en la zona del Arenal. Kayak en el lago por la mañana, Parque Nacional por la tarde y termas de noche.',
    accommodation: 'Lucky Bug Bed & Breakfast',
    meals: {
      breakfast: 'Desayuno en el hotel',
      lunch: 'Lava Lounge — hamburguesas y vistas',
      dinner: 'Don Rufino — el mejor de La Fortuna',
    },
    activities: [
      { time: '07:30', name: 'Kayak en Lago Arenal', duration: '2.5h', cost: 35, note: 'Mejor con agua calma por la mañana' },
      { time: '11:00', name: 'Parque Nacional Volcán Arenal — sendero Los Tucanes', duration: '2h', cost: 20 },
      { time: '14:00', name: 'Almuerzo y descanso', duration: '1.5h', cost: 18 },
      { time: '17:00', name: 'Eco Termales Hot Springs', duration: '3h', cost: 45, note: 'Más tranquilo que Tabacón y mejor precio' },
      { time: '20:30', name: 'Cena en Don Rufino', duration: '1.5h', cost: 25 },
    ],
    drivingToNext: { destination: 'Monteverde (vía transbordador o ruta)', km: 75, hours: 3.5 },
    tips: ['Eco Termales es mejor que Tabacón — menos gente y mejor relación precio-calidad', 'Reservá las termas con al menos 2 días de anticipación', 'El sendero del Parque Nacional cierra a las 16:00'],
    budget: { accommodation: 75, food: 65, activities: 100, transport: 10, total: 250 },
  },
  {
    day: 4,
    date: '2026-01-19',
    title: 'Arenal → Monteverde (transbordador)',
    emoji: '⛵',
    region: 'Monteverde',
    lat: 10.2994,
    lng: -84.8198,
    theme: 'El transbordador del Lago + bosque nuboso',
    description: 'Cruce en transbordador por el Lago Arenal — la ruta más pintoresca. Llegada a Monteverde, tarde libre para explorar Santa Elena.',
    accommodation: 'Camino Verde B&B',
    meals: {
      breakfast: 'Desayuno en Lucky Bug',
      lunch: 'En el transbordador o snack',
      dinner: 'Morpho\'s Restaurant — Santa Elena',
    },
    activities: [
      { time: '07:00', name: 'Salida hacia el transbordador de Río Chiquito', duration: '1h drive', cost: 0 },
      { time: '08:30', name: 'Transbordador Lago Arenal', duration: '1h', cost: 15, note: 'Precio del bote, auto aparte ~$5' },
      { time: '10:00', name: 'Ruta a Monteverde (camino de tierra)', duration: '2.5h', cost: 0, note: 'El 4x4 vale todo acá' },
      { time: '13:00', name: 'Check-in y almuerzo en Santa Elena', duration: '2h', cost: 15 },
      { time: '15:00', name: 'Paseo por el pueblo de Santa Elena — chocolate local, café', duration: '2h', cost: 20 },
      { time: '18:30', name: 'Cena en Morpho\'s', duration: '1.5h', cost: 20 },
    ],
    drivingToNext: { destination: 'Continúa en Monteverde', km: 0, hours: 0 },
    tips: ['Salí antes de las 7:30 para el primer bote', 'El camino de tierra a Monteverde tiene pozos — el 4x4 es obligatorio', 'Comprá el chocolate Monteverde directamente en la fábrica'],
    budget: { accommodation: 60, food: 55, activities: 20, transport: 25, total: 160 },
  },
  {
    day: 5,
    date: '2026-01-20',
    title: 'Monteverde — Bosque Nuboso y Tirolesas',
    emoji: '🌿',
    region: 'Monteverde',
    lat: 10.2994,
    lng: -84.8198,
    theme: 'El bosque más mágico de Costa Rica',
    description: 'Día completo en la Reserva Biológica Bosque Nuboso. Mañana con guía para ver quetzales y orquídeas, tarde de tirolesas.',
    accommodation: 'Camino Verde B&B',
    meals: {
      breakfast: 'Desayuno en Camino Verde',
      lunch: 'Café Monteverde — dentro de la reserva',
      dinner: 'El Jardín — cocina fusión',
    },
    activities: [
      { time: '06:30', name: 'Tour guiado amanecer — Reserva Bosque Nuboso', duration: '3h', cost: 45, note: 'Con guía es imprescindible para ver quetzales' },
      { time: '10:00', name: 'Puentes Colgantes de Monteverde', duration: '2h', cost: 26, note: 'Vistas increíbles del bosque desde arriba' },
      { time: '13:00', name: 'Almuerzo en Café Monteverde', duration: '1h', cost: 15 },
      { time: '14:30', name: 'Sky Adventures — Tirolesas', duration: '3h', cost: 75, note: 'El Sky Trek tiene las tirolesas más largas' },
      { time: '19:00', name: 'Cena tranquila en El Jardín', duration: '1.5h', cost: 22 },
    ],
    drivingToNext: { destination: 'Manuel Antonio (vía Puente de los Cocodrilos)', km: 190, hours: 3.5 },
    tips: ['Reservá el tour de quetzales con 2 días mínimo de anticipación', 'El Sky Trek es caro pero vale la pena — ¡son 10 cables!', 'Llevá abrigo liviano, en el bosque hace frío aunque sea enero'],
    budget: { accommodation: 60, food: 55, activities: 146, transport: 10, total: 271 },
  },
  {
    day: 6,
    date: '2026-01-21',
    title: 'Monteverde → Manuel Antonio',
    emoji: '🐊',
    region: 'Pacífico Central',
    lat: 9.3860,
    lng: -84.1719,
    theme: 'Cocodrilos, playa y selva',
    description: 'Bajada al Pacífico. Parada imperdible en el Puente Tarcoles para ver cocodrilos. Llegada a Manuel Antonio antes de la tarde.',
    accommodation: 'Backpackers Manuel Antonio',
    meals: {
      breakfast: 'Desayuno en Camino Verde',
      lunch: 'La Cantina — Jacó (parada en el camino)',
      dinner: 'El Avión — Manuel Antonio (restaurante en un avión)',
    },
    activities: [
      { time: '07:30', name: 'Salida de Monteverde hacia Manuel Antonio', duration: '3.5h', cost: 0 },
      { time: '10:30', name: 'Parada Puente Tarcoles — cocodrilos', duration: '45min', cost: 0, note: 'Gratis, pero hay "guachimanes" — dales propina' },
      { time: '12:00', name: 'Almuerzo en Jacó (parada rápida)', duration: '1h', cost: 15 },
      { time: '14:00', name: 'Llegada y check-in Manuel Antonio', duration: '1h', cost: 0 },
      { time: '15:30', name: 'Primera visita a Playa Biesanz', duration: '2h', cost: 0, note: 'La playa escondida más linda de la zona' },
      { time: '19:00', name: 'Cena en El Avión — restaurante dentro de un avión Fairchild', duration: '2h', cost: 30 },
    ],
    drivingToNext: { destination: 'Continúa en Manuel Antonio', km: 0, hours: 0 },
    tips: ['Reservá El Avión para la cena — es uno de los mejores de Costa Rica', 'Playa Biesanz está escondida — buscala en Google Maps exactamente', 'El tramo Monteverde-Jacó tiene algunas curvas bravísimas'],
    budget: { accommodation: 35, food: 65, activities: 0, transport: 30, total: 130 },
  },
  {
    day: 7,
    date: '2026-01-22',
    title: 'Parque Nacional Manuel Antonio',
    emoji: '🐒',
    region: 'Manuel Antonio',
    lat: 9.3860,
    lng: -84.1719,
    theme: 'Monos, perezosos y playas vírgenes',
    description: 'El parque nacional más visitado de Costa Rica. Fauna a metros del agua, playas de película y el mejor snorkel de la zona.',
    accommodation: 'Backpackers Manuel Antonio',
    meals: {
      breakfast: 'Fruta del mercado local',
      lunch: 'Dentro del parque — traé tu propia comida o hay un pequeño kiosco',
      dinner: 'La Luna — cena con vista al Pacífico',
    },
    activities: [
      { time: '07:00', name: 'Apertura del Parque Nacional Manuel Antonio', duration: '5h', cost: 20, note: 'Reservá online obligatorio — se agota' },
      { time: '07:30', name: 'Sendero El Perezoso — avistamiento de fauna', duration: '2h', cost: 0 },
      { time: '10:00', name: 'Playa Manuel Antonio — snorkel y nado', duration: '2.5h', cost: 0 },
      { time: '13:00', name: 'Almuerzo frugal y descanso en la playa', duration: '1.5h', cost: 10 },
      { time: '15:00', name: 'Playa Espadilla — tarde libre', duration: '2.5h', cost: 0 },
      { time: '19:30', name: 'Cena en La Luna con sunset', duration: '2h', cost: 28 },
    ],
    drivingToNext: { destination: 'Continúa en Manuel Antonio', km: 0, hours: 0 },
    tips: ['Las entradas al parque se agotan — reservá en sinac.go.cr con 1 semana de anticipación', 'Los monos capuchinos son ladrones de comida — no dejes bolsos abiertos', 'Llegá a las 7am para ver más fauna antes del calor'],
    budget: { accommodation: 35, food: 45, activities: 20, transport: 0, total: 100 },
  },
  {
    day: 8,
    date: '2026-01-23',
    title: 'Manuel Antonio — Día de playa libre',
    emoji: '🏄',
    region: 'Manuel Antonio',
    lat: 9.3860,
    lng: -84.1719,
    theme: 'Surf, descanso y atardecer',
    description: 'Día completamente libre. Mañana de surf en Playa Espadilla, tarde de hamaca y atardecer con cócteles.',
    accommodation: 'Backpackers Manuel Antonio',
    meals: {
      breakfast: 'Soda local frente al mar',
      lunch: 'La Cantina Quepos — mar afuera',
      dinner: 'Agua Azul — terraza sobre el océano',
    },
    activities: [
      { time: '08:00', name: 'Clase de surf en Playa Espadilla', duration: '2h', cost: 35, note: 'Instructores locales muy buenos y baratos' },
      { time: '11:00', name: 'Descanso en la playa, hamaca', duration: '3h', cost: 0 },
      { time: '15:00', name: 'Tour de kayak marino y snorkel', duration: '2.5h', cost: 45, note: 'Hermosos corales cerca de Manuel Antonio' },
      { time: '18:30', name: 'Sunset bar en terraza', duration: '1.5h', cost: 20 },
      { time: '20:00', name: 'Cena en Agua Azul', duration: '2h', cost: 25 },
    ],
    drivingToNext: { destination: 'Uvita / Bahía Ballena', km: 85, hours: 1.5 },
    tips: ['Playa Espadilla es pública y sin costo de entrada', 'El kayak marino al amanecer o al atardecer es espectacular', 'Quepos tiene buena vida nocturna si quieren salir de noche'],
    budget: { accommodation: 35, food: 60, activities: 100, transport: 0, total: 195 },
  },
  {
    day: 9,
    date: '2026-01-24',
    title: 'Manuel Antonio → Uvita',
    emoji: '🐋',
    region: 'Pacífico Sur',
    lat: 9.1516,
    lng: -83.7329,
    theme: 'La Cola de Ballena',
    description: 'Viaje corto al Pacífico Sur. Uvita es menos conocida y más tranquila que Manuel Antonio. Playa en forma de ballena, snorkel y delfines.',
    accommodation: 'Tucan Hotel Uvita',
    meals: {
      breakfast: 'Desayuno en Manuel Antonio',
      lunch: 'La Cantina Uvita — ceviche fresco',
      dinner: 'Phat Noodle — fusión asiática inesperadamente buena',
    },
    activities: [
      { time: '09:00', name: 'Salida hacia Uvita — ruta costera hermosa', duration: '1.5h', cost: 0 },
      { time: '11:00', name: 'Check-in y llegada a Uvita', duration: '1h', cost: 0 },
      { time: '12:30', name: 'Almuerzo de ceviche en el pueblo', duration: '1h', cost: 15 },
      { time: '14:00', name: 'Parque Nacional Marino Ballena — Cola de Ballena', duration: '3h', cost: 18, note: 'La formación de la playa con marea baja es IMPRESIONANTE' },
      { time: '17:30', name: 'Sunset desde la Cola de la Ballena', duration: '1h', cost: 0, note: 'Uno de los mejores sunsets de Costa Rica' },
      { time: '19:30', name: 'Cena tranquila en Uvita', duration: '1.5h', cost: 18 },
    ],
    drivingToNext: { destination: 'Continúa en Uvita', km: 0, hours: 0 },
    tips: ['La Cola de Ballena solo es visible con marea baja — chequeá el horario antes', 'De enero a marzo hay avistamiento de ballenas jorobadas', 'Uvita es pequeño y tranquilo — ideal para descansar'],
    budget: { accommodation: 45, food: 45, activities: 18, transport: 20, total: 128 },
  },
  {
    day: 10,
    date: '2026-01-25',
    title: 'Uvita — Ballenas y Snorkel',
    emoji: '🤿',
    region: 'Pacífico Sur',
    lat: 9.1516,
    lng: -83.7329,
    theme: 'El océano es el protagonista',
    description: 'Tour en bote de avistamiento de ballenas y delfines por la mañana, tarde libre en Uvita.',
    accommodation: 'Tucan Hotel Uvita',
    meals: {
      breakfast: 'Desayuno en el hotel',
      lunch: 'Mariscos frescos en el puerto pesquero',
      dinner: 'En el hotel o soda local',
    },
    activities: [
      { time: '07:00', name: 'Tour avistamiento de ballenas y delfines', duration: '4h', cost: 75, note: 'Enero es temporada perfecta para ballenas jorobadas' },
      { time: '12:00', name: 'Almuerzo en el muelle con mariscos frescos', duration: '1h', cost: 20 },
      { time: '14:00', name: 'Tarde libre — playa, hamaca, lectura', duration: '3h', cost: 0 },
      { time: '17:00', name: 'Cascada Uvita (5 min del pueblo)', duration: '1.5h', cost: 5 },
      { time: '19:30', name: 'Cena sencilla', duration: '1h', cost: 15 },
    ],
    drivingToNext: { destination: 'San José (vuelta)', km: 250, hours: 4 },
    tips: ['Bahía Aventuras es la mejor empresa para el tour de ballenas', 'El tour incluye snorkel — llevá tu antiparras si tenés', 'La Cascada Uvita está a 2km del pueblo y casi nadie la conoce'],
    budget: { accommodation: 45, food: 40, activities: 80, transport: 5, total: 170 },
  },
  {
    day: 11,
    date: '2026-01-26',
    title: 'Uvita → San José (día de tránsito)',
    emoji: '🚗',
    region: 'Ruta Costera',
    lat: 9.5000,
    lng: -84.0000,
    theme: 'La ruta costera y última parada',
    description: 'Viaje de vuelta a San José. Parada opcional en Dominical (playa de surfistas) y en el mercado de Jaco.',
    accommodation: 'Hotel Presidente San José',
    meals: {
      breakfast: 'Desayuno en Uvita antes de salir',
      lunch: 'Dominical — soda frente al mar',
      dinner: 'San José — Restaurante Nuestra Tierra (costillas ticas y marimba)',
    },
    activities: [
      { time: '08:00', name: 'Salida de Uvita', duration: '0', cost: 0 },
      { time: '09:30', name: 'Parada en Dominical — playa de surf', duration: '1.5h', cost: 0 },
      { time: '12:00', name: 'Almuerzo frente al mar en Dominical', duration: '1h', cost: 15 },
      { time: '13:30', name: 'Continuación hacia San José', duration: '2.5h', cost: 0 },
      { time: '16:30', name: 'Llegada, check-in Hotel Presidente', duration: '1h', cost: 0 },
      { time: '19:00', name: 'Cena despedida provisional en Nuestra Tierra', duration: '2h', cost: 22 },
    ],
    drivingToNext: { destination: 'Continúa en San José', km: 0, hours: 0 },
    tips: ['Nuestra Tierra es el restaurante más típico de San José — con marimba en vivo', 'Devolvé el auto al día siguiente temprano para evitar cargos extra', 'Hotel Presidente está en el centro histórico — todo a pie'],
    budget: { accommodation: 80, food: 50, activities: 0, transport: 40, total: 170 },
  },
  {
    day: 12,
    date: '2026-01-27',
    title: 'San José — Cultura y Mercado Central',
    emoji: '🏛️',
    region: 'San José',
    lat: 9.9281,
    lng: -84.0907,
    theme: 'La capital que sorprende',
    description: 'Día cultural en San José. Museos, Mercado Central, barrios históricos y el mejor café de exportación.',
    accommodation: 'Hotel Presidente San José',
    meals: {
      breakfast: 'Desayuno en el hotel',
      lunch: 'Mercado Central — sopa de mariscos o casado',
      dinner: 'Park Café — cocina de autor, imperdible',
    },
    activities: [
      { time: '09:00', name: 'Museo del Oro Precolombino', duration: '2h', cost: 11, note: 'Colección impresionante de oro indígena' },
      { time: '11:30', name: 'Teatro Nacional — tour arquitectónico', duration: '1h', cost: 10 },
      { time: '13:00', name: 'Mercado Central — almuerzo y souvenirs', duration: '2h', cost: 15 },
      { time: '15:30', name: 'Barrio Amón y Barrio Otoya — street art y cafés', duration: '2h', cost: 10 },
      { time: '18:30', name: 'Compras finales — café, ron Centenario, chocolates', duration: '1h', cost: 30 },
      { time: '20:00', name: 'Cena en Park Café', duration: '2h', cost: 35 },
    ],
    drivingToNext: { destination: 'Continúa en San José', km: 0, hours: 0 },
    tips: ['El café Britt y Volio son los mejores souvenirs', 'El Museo del Oro es uno de los mejores de Centroamérica', 'Reservá Park Café con anticipación — solo 8 mesas'],
    budget: { accommodation: 80, food: 65, activities: 56, transport: 10, total: 211 },
  },
  {
    day: 13,
    date: '2026-01-28',
    title: 'Volcán Poás (excursión de día)',
    emoji: '🌋',
    region: 'Valle Central',
    lat: 10.1966,
    lng: -84.2286,
    theme: 'El cráter más accesible del mundo',
    description: 'Excursión de día al Volcán Poás, el cráter activo más accesible del mundo. Vuelta al hotel para la noche.',
    accommodation: 'Hotel Presidente San José',
    meals: {
      breakfast: 'Desayuno en el hotel — salida temprana',
      lunch: 'Restaurante La Colina — cerca del volcán, con vista',
      dinner: 'El Balcón de Europa — pasta italiana en San José',
    },
    activities: [
      { time: '06:30', name: 'Salida hacia Volcán Poás', duration: '1.5h drive', cost: 0 },
      { time: '08:00', name: 'Apertura del Parque Nacional Volcán Poás', duration: '3h', cost: 18, note: 'Reservá online — solo 120 personas por hora' },
      { time: '09:00', name: 'Sendero al cráter principal', duration: '1h', cost: 0, note: 'Cráter turquesa impresionante' },
      { time: '10:30', name: 'Laguna Botos (lago cratérico)', duration: '1h', cost: 0 },
      { time: '12:30', name: 'Almuerzo con vista al volcán', duration: '1.5h', cost: 20 },
      { time: '14:30', name: 'Regreso a San José — opcional: Catarata de La Paz', duration: '2h', cost: 30 },
      { time: '19:00', name: 'Cena tranquila en San José', duration: '2h', cost: 22 },
    ],
    drivingToNext: { destination: 'Continúa en San José', km: 0, hours: 0 },
    tips: ['El volcán se cubre de nubes después de las 10am — llegá bien temprano', 'La Catarata de La Paz tiene mariposas, tucanes y colibríes — vale el desvío', 'Reservá el parque en sinac.go.cr 1 semana antes'],
    budget: { accommodation: 80, food: 55, activities: 48, transport: 30, total: 213 },
  },
  {
    day: 14,
    date: '2026-01-29',
    title: 'Día libre en San José + compras finales',
    emoji: '🛍️',
    region: 'San José',
    lat: 9.9281,
    lng: -84.0907,
    theme: 'Último día de aventura',
    description: 'Día libre en San José. Compras de souvenirs, spa opcional, o excursión a los cafetales de Dota.',
    accommodation: 'Hotel Presidente San José',
    meals: {
      breakfast: 'Desayuno en el hotel',
      lunch: 'Cafetería Ruiseñor — brunch',
      dinner: 'Cena de despedida — Sikwa (cocina indígena de Costa Rica)',
    },
    activities: [
      { time: '09:00', name: 'Excursión opcional: Cafetales de Santa María de Dota', duration: '4h', cost: 45, note: 'El mejor café del mundo está acá' },
      { time: '14:00', name: 'Compras en Mercado de Artesanías', duration: '2h', cost: 40 },
      { time: '16:30', name: 'Spa o tiempo libre en el hotel', duration: '2h', cost: 0 },
      { time: '20:00', name: 'Cena de despedida en Sikwa — cocina indígena', duration: '2h', cost: 35, note: 'Experiencia gastronómica única — reservá' },
    ],
    drivingToNext: { destination: 'Aeropuerto SJO', km: 20, hours: 0.5 },
    tips: ['Sikwa es el único restaurante de cocina indígena de San José — imperdible', 'Comprá café en grano directamente en las cooperativas de Dota', 'Dejá listos los bolsos la noche antes del vuelo'],
    budget: { accommodation: 80, food: 65, activities: 85, transport: 10, total: 240 },
  },
  {
    day: 15,
    date: '2026-01-30',
    title: 'Vuelta a casa ✈️',
    emoji: '🏠',
    region: 'San José',
    lat: 9.9986,
    lng: -84.2088,
    theme: 'Pura vida, para siempre',
    description: 'Desayuno tranquilo y traslado al aeropuerto. La pura vida se lleva en el alma.',
    accommodation: null,
    meals: {
      breakfast: 'Último gallo pinto en el hotel',
      lunch: 'En el aeropuerto o el avión',
      dinner: 'En el avión / Buenos Aires',
    },
    activities: [
      { time: '08:00', name: 'Desayuno y últimas fotos del hotel', duration: '1h', cost: 0 },
      { time: '10:00', name: 'Check-out y traslado al aeropuerto SJO', duration: '45min', cost: 20, note: 'Taxi o Uber desde el centro — ~$20' },
      { time: '11:00', name: 'Llegada al aeropuerto — check-in', duration: '2h', cost: 0, note: 'Llegá 3 horas antes para vuelos internacionales' },
      { time: '14:00', name: 'Vuelo SJO → Buenos Aires', duration: '~10h', cost: 0 },
    ],
    drivingToNext: null,
    tips: ['El taxi al aeropuerto desde el centro sale ~$20 — acordalo con anticipación', 'Usá los colones que te sobren en el aeropuerto antes de pasar seguridad', '¡Guardá las fotos en la nube antes de volar!'],
    budget: { accommodation: 0, food: 20, activities: 0, transport: 20, total: 40 },
  },
]
